apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ativ4-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-ativ4
  template:
    metadata:
      labels:
        app: app-ativ4
    spec:
      containers:
      - name: admokd-ativ2-container
        image: isaacrsjr/adm_okd_ativ2:v3
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
              name: app-ativ4-cfgmap
