apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ativ4
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-ativ4
  template:
    metadata:
      labels:
        app: app-ativ4
        
    