apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-ativ4-hpa
  namespace: univates
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-ativ4-dep
  targetCPUUtilizationPercentage: 10
